## NumPy Library

- NumPy stands for numerical python
- NumPy is used for liner algebra operations

## Install NumPy
- In command prompt type the following command to install numpy
```
pip install numpy
```
- In jupyter to install numpy use the following command

```
pip install numpy
```

### Using NumPy by imporanting it

In [1]:
import numpy

### What are you going to do with numpy library
- we create arrays (numerical arrays) with many dimensions
- Such arrays are called ndarrays

### Import import with an alias name `np`

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])

arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Four Basic attributes of numpy arrays

In [6]:
arr1

array([1, 2, 3, 4])

#### shape attribute gives on tuple with values to specify the shape

In [7]:
arr1 .shape

(4,)

In [8]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
arr2.shape

(4, 3)

### `ndim` to get number of dimensions

In [10]:
arr1

array([1, 2, 3, 4])

In [11]:
arr1.ndim

1

In [12]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr2.ndim

2

#### `soze` to get total number of element

In [14]:
arr1

array([1, 2, 3, 4])

In [15]:
arr1.size

4

In [16]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr2.size

12

#### `dtype` - to know the datatype of the element of an array

In [18]:
arr1

array([1, 2, 3, 4])

In [19]:
arr1.dtype

dtype('int64')

In [20]:
arr2.dtype

dtype('int64')

#### `ones()` to create a array with ones

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

#### `zeros()` to create an arrays with all zero

In [23]:
np.zeros((5,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 
`full()` to create an array with a default (fixed) values

In [24]:
np.full((4,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

#### `eye()` to create an identity matrix (arrry)

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### createing array with seduence of integers using - `arange()`
##### syntax
```
arange([start,, ]stop[,step])
```

- By default start is 0; and stop is 1
- stop is requried

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [30]:
np.arange(-100, 100, 25)

array([-100,  -75,  -50,  -25,    0,   25,   50,   75])

#### create a sequence of number that equally distant from each other using - `linspace`

    linspace(start, stop, num_of_values)

In [31]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Generate random values between 0 and 1 ,1 is exlusive

    np.random.rand(rows, cols)

In [32]:
np.random.rand(4, 3)

array([[0.92562969, 0.49914264, 0.14743474],
       [0.49131092, 0.59802959, 0.559205  ],
       [0.17315136, 0.17655956, 0.51395958],
       [0.31227879, 0.62984261, 0.30186609]])

#### Generate an array with normal distribution

In [33]:
np.random.rand(3,5)

array([[0.45410647, 0.75437258, 0.26805572, 0.38440332, 0.08918027],
       [0.42063121, 0.12063906, 0.39794457, 0.73266191, 0.95119827],
       [0.22542198, 0.51790783, 0.14762366, 0.54348625, 0.22073254]])

#### Generate on array with random numder 

In [34]:
np.random.randint(0, 10,(4, 8))

array([[7, 2, 1, 9, 6, 2, 8, 3],
       [7, 5, 9, 5, 2, 7, 7, 4],
       [2, 7, 3, 1, 7, 9, 9, 6],
       [6, 4, 5, 8, 5, 4, 8, 3]], dtype=int32)

#### Changing types of an array

In [35]:
arr = np.array([1.2,2.3,3.4,4.5])
arr.dtype

dtype('float64')

In [36]:
arr = arr.astype(int)
arr

array([1, 2, 3, 4])

In [37]:
arr.dtype

dtype('int64')

## INDEXING AND SLICING

In [38]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[0])

10


In [39]:
print(arr1[-1])

50


In [40]:
arr2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [41]:
arr2[0, :]

array([1, 2, 3])

In [42]:
arr2[1, 2]

np.int64(6)

In [43]:
arr2[:, 1]

array([2, 5, 8])

In [44]:
arr2[1:, 1:]

array([[5, 6],
       [8, 9]])

#### Boolean indexing

In [45]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [46]:
mask

array([False, False, False,  True,  True])

#### Fancy indexing

In [47]:
arr

array([1, 2, 3, 4, 5])

In [48]:
indexes = [0, 3, 4]
arr[indexes]

array([1, 4, 5])

#### Reshaping an array using reshape(rows,cols)method

In [49]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
arr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [51]:
arr.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [52]:
arr.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
arr = arr.reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### `flatten` - make an array one-dimensional

In [55]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## NumPy operations

#### Element-wise Arithmetices

In [56]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [57]:
print(a+b)

[5 7 9]


In [58]:
print(a/b)

[0.25 0.4  0.5 ]


In [59]:
print(a**b)

[  1  32 729]


# Working with scalars

In [60]:
a+10

array([11, 12, 13])

In [61]:
b - 3

array([1, 2, 3])

In [62]:
a/b

array([0.25, 0.4 , 0.5 ])

### Universal functions

In [63]:
arr = np.array([1, 4, 9, 16])

In [64]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [65]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [70]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [71]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [72]:
np.cos(arr)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948])

#### Aggregate functions

In [74]:
arr = np.array([
    [1,2,3],
    [4,5,6],
])

In [75]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr.sum()

np.int64(21)

#### axis - dimensions 2 (rows and columns) - axes (x-axis is 0 ,y-axis is 1)

In [80]:
arr.sum(axis = 0)

array([5, 7, 9])

In [81]:
arr.sum(axis = 1)

array([ 6, 15])

In [ ]:
# mean(), max(), count()

In [84]:
arr.mean()

np.float64(3.5)

In [88]:
arr.max()

np.int64(6)

In [90]:
arr.min()

np.int64(1)

#### Broadcasting

In [91]:
# performing operations on unequal arrays

In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
add_vector = np.array([10, 20, 30])
add_vector

array([10, 20, 30])

#### comparison opertors

In [98]:
arr = np.array([1,2,3,4,5])
arr >= 3

array([False, False,  True,  True,  True])

In [99]:
arr == 3

array([False, False,  True, False, False])

In [100]:
arr != 3

array([ True,  True, False,  True,  True])

In [101]:
arr > 0

array([ True,  True,  True,  True,  True])

In [102]:
### Any() and all functions 

In [107]:
np.any(arr == 3)   # if atleast one value is true it returns True

np.True_

In [110]:
np.all(arr == 3)   # if at value one value is False it returns False

np.False_

In [111]:
np.all(arr>0)

np.True_

In [112]:
np.all(arr<0)

np.False_

#### conditional selection (where)

In [116]:
arr = np.array([10,20,30,40])
result = np.where(arr > 25,1,0)   # 1 represent True; 0 represent False
result


array([0, 0, 1, 1])

In [117]:
#### Non-zero Selection 
arr = np.array([3, 0, 1, 4, 0])
index = np.nonzero(arr)
arr[index]

array([3, 1, 4])

#### sort the elements

In [122]:
arr = np.array([
    [3, 1, 9],
    [8, 7, 6],
])
arr

array([[3, 1, 9],
       [8, 7, 6]])

In [123]:
np.sort(arr)

array([[1, 3, 9],
       [6, 7, 8]])

In [124]:
np.sort(arr, axis=0)

array([[3, 1, 6],
       [8, 7, 9]])

In [125]:
np.sort(arr, axis=0)

array([[3, 1, 6],
       [8, 7, 9]])

#### stackind arrays

In [126]:
a = np.array([10, 20, 30])
b = np.array([15, 25, 35])

In [127]:
# vertical stacking
np.vstack((a,b))

array([[10, 20, 30],
       [15, 25, 35]])

In [128]:
# horizontal stacking
np.hstack((a,b))

array([10, 20, 30, 15, 25, 35])

In [129]:
# column stacking
np.column_stack((a,b))

array([[10, 15],
       [20, 25],
       [30, 35]])

#### Splitting 

In [130]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.split(arr, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [135]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])
np.vsplit(arr, 2)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

#### Matrix multiplication

In [137]:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [138]:
# alternatively
A @ B

array([[19, 22],
       [43, 50]])

In [139]:
#### Transpose

In [140]:
A

array([[1, 2],
       [3, 4]])

In [141]:
A.T  # T attribute is used to transpose a matrix

array([[1, 3],
       [2, 4]])

In [142]:
#### Inverse Matrix

In [145]:
A = np.array([
    [4,5],
    [10,7]
])

inv_A = np.linalg.inv(A)
inv_A

array([[-0.31818182,  0.22727273],
       [ 0.45454545, -0.18181818]])

In [146]:
A @ inv_A

array([[ 1.00000000e+00, -1.11022302e-16],
       [-4.44089210e-16,  1.00000000e+00]])

#### Determinent of a Matrix

In [147]:
A

array([[ 4,  5],
       [10,  7]])

In [149]:
 np.linalg.det(A)

np.float64(-22.000000000000004)

#### EigenValues and EigenVectors

In [151]:
A  # squre matrix

array([[ 4,  5],
       [10,  7]])

In [163]:
values, vectors =  np.linalg.eig(A)
print("Values:", values)
print("Vector:", vectors)

Values: [-1.72841615 12.72841615]
Vector: [[-0.65758314 -0.49706296]
 [ 0.75338198 -0.86771448]]


In [159]:
#### Norm (Vector Magnitude)

In [160]:
A

array([[ 4,  5],
       [10,  7]])

In [161]:
 np.linalg.norm(A)

np.float64(13.784048752090222)